# Generated by Django 2.2.1 on 2019-05-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AML', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookinfo',
            name='page_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
